# Generated by Django 6.1.1 on 2026-09-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='lectures/videos'),
        ),
    ]
