# Generated by Django 6.1.1 on 2026-09-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_alter_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('transcribing', 'Transcribing'), ('processing_slides', 'Processing Slides'), ('generating_notes', 'Generating Notes'), ('generating_quiz', 'Generating Quiz'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=30),
        ),
    ]
