# Generated by Django 6.1.1 on 2026-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_alter_lecture_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slides_source',
            field=models.FileField(blank=True, max_length=3000, null=True, upload_to='lectures/slide_sources/'),
        ),
    ]
