# Generated by Django 6.1.1 on 2026-09-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0005_audiosegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('text', models.TextField()),
                ('avg_logprob', models.FloatField(blank=True, null=True)),
                ('no_speech_prob', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcript_segments', to='lectures.audiosegment')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
