# Generated by Django 6.1.1 on 2026-09-09 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0006_transcriptsegment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='lectures/slides/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='lectures.lecture')),
            ],
            options={
                'ordering': ['slide_number'],
                'constraints': [models.UniqueConstraint(fields=('lecture', 'slide_number'), name='unique_lecture_slide_number')],
            },
        ),
    ]
